all: comm_progs

comm_progs:
	g++ contenful.cpp -o contenful.exe -lcurl

# cd C:/Users/dandi/"OneDrive - Estudiantes ITCR"/Documentos/TEC/"II Semestre"/"Estructura de Datos"/Caso5/socket
# apt update -y
# app install curl