all: comm_progs

comm_progs:
	g++ contenful.cpp -o contenful.exe -lcurl
	./contenful.exe
# cd C:/Users/Dandiego/"OneDrive - Estudiantes ITCR"/"Estructuras de datos"/Caso5/socket
# apt update -y
# app install curl